### ISSUE TITLE
Empty file generated when running in Nx monorepo

### ISSUE THREAD

**Issue by christowiz** [sumy7/vite-plugin-generate-file#6]
When running a build command using Vite from within an Nx monorepo an empty file is created.  This doesn't happen in a standard Git repository.

Example repo:
https://github.com/christowiz/generate-file/

**Comment by sumy7** [comment]
Hi @christowiz ,
Thank you for your feedback. I've also tried it myself and indeed encountered the same issue.
It appears that simply removing the `nxViteTsPaths` plugin resolves the problem.

My guess is that the issue might be due to the `vite-plugin-generate-file` plugin being terminated before it has finished writing the file.
To prevent this from happening in the future, we're considering changing the file writing operation from asynchronous to synchronous. I'll address this issue shortly.

**Comment by sumy7** [comment]
Hi @christowiz,
I have changed the file writing method from asynchronous to synchronous and released version 0.2.0.
Could you please try this version and see if the issue still occurs?

Thank you again for your feedback.

**Comment by christowiz** [comment]
Thanks, @sumy7.  We're manually handling the file writing but I'll try with the update.  Appreciate it.
